# Form implementation generated from reading ui file 'c:\Users\Justin\Mi-Create\src\dialog\resourceDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

sys.path.append("..")

from coreGettext import QCoreApplication


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 300)
        Dialog.setMinimumSize(QtCore.QSize(100, 225))
        Dialog.setMaximumSize(QtCore.QSize(300, 300))
        Dialog.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.addImage = QtWidgets.QToolButton(parent=Dialog)
        self.addImage.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Dark/file-plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addImage.setIcon(icon)
        self.addImage.setObjectName("addImage")
        self.gridLayout.addWidget(self.addImage, 1, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.imageSelect = QtWidgets.QListWidget(parent=self.page)
        self.imageSelect.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.imageSelect.setIconSize(QtCore.QSize(64, 64))
        self.imageSelect.setUniformItemSizes(False)
        self.imageSelect.setObjectName("imageSelect")
        self.gridLayout_2.addWidget(self.imageSelect, 1, 0, 1, 3)
        self.searchLabel = QtWidgets.QLabel(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLabel.sizePolicy().hasHeightForWidth())
        self.searchLabel.setSizePolicy(sizePolicy)
        self.searchLabel.setObjectName("searchLabel")
        self.gridLayout_2.addWidget(self.searchLabel, 0, 0, 1, 1)
        self.searchBar = QtWidgets.QLineEdit(parent=self.page)
        self.searchBar.setClearButtonEnabled(True)
        self.searchBar.setObjectName("searchBar")
        self.gridLayout_2.addWidget(self.searchBar, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select resource..."))
        self.addImage.setText(_translate("Dialog", "..."))
        self.searchLabel.setText(_translate("Dialog", "Search:"))
