# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QTabWidget,
    QToolBar, QWidget)
import resources.icons_rc as icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1250, 750)
        MainWindow.setMinimumSize(QSize(750, 750))
        icon = QIcon()
        icon.addFile(u":/Dark/MiFaceStudioFavicon.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/Dark/MiFaceStudioFavicon.png", QSize(), QIcon.Normal, QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionAbout_MiFaceStudio = QAction(MainWindow)
        self.actionAbout_MiFaceStudio.setObjectName(u"actionAbout_MiFaceStudio")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionCompile = QAction(MainWindow)
        self.actionCompile.setObjectName(u"actionCompile")
        self.actionshowAboutWindow = QAction(MainWindow)
        self.actionshowAboutWindow.setObjectName(u"actionshowAboutWindow")
        self.actionshowDefaultInfoDialog = QAction(MainWindow)
        self.actionshowDefaultInfoDialog.setObjectName(u"actionshowDefaultInfoDialog")
        self.actionExplorer = QAction(MainWindow)
        self.actionExplorer.setObjectName(u"actionExplorer")
        self.actionExplorer.setCheckable(True)
        self.actionExplorer.setChecked(True)
        self.actionAttributes = QAction(MainWindow)
        self.actionAttributes.setObjectName(u"actionAttributes")
        self.actionAttributes.setCheckable(True)
        self.actionAttributes.setChecked(True)
        self.actionResources = QAction(MainWindow)
        self.actionResources.setObjectName(u"actionResources")
        self.actionResources.setCheckable(True)
        self.actionResources.setChecked(True)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionshowToast = QAction(MainWindow)
        self.actionshowToast.setObjectName(u"actionshowToast")
        self.actionToolbox = QAction(MainWindow)
        self.actionToolbox.setObjectName(u"actionToolbox")
        self.actionToolbox.setCheckable(True)
        self.actionToolbox.setChecked(True)
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionEdit.setCheckable(True)
        self.actionEdit.setChecked(True)
        self.actionFile = QAction(MainWindow)
        self.actionFile.setObjectName(u"actionFile")
        self.actionFile.setCheckable(True)
        self.actionFile.setChecked(True)
        self.actionLayout = QAction(MainWindow)
        self.actionLayout.setObjectName(u"actionLayout")
        self.actionLayout.setCheckable(True)
        self.actionLayout.setChecked(True)
        self.actionNewFile = QAction(MainWindow)
        self.actionNewFile.setObjectName(u"actionNewFile")
        icon1 = QIcon()
        icon1.addFile(u":/Dark/file-plus-2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNewFile.setIcon(icon1)
        self.actionOpenFile = QAction(MainWindow)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        icon2 = QIcon()
        icon2.addFile(u":/Dark/folder-open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpenFile.setIcon(icon2)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon3 = QIcon()
        icon3.addFile(u":/Dark/undo-2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon3)
        self.actionUndo.setMenuRole(QAction.NoRole)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon4 = QIcon()
        icon4.addFile(u":/Dark/redo-2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon4)
        self.actionRedo.setMenuRole(QAction.NoRole)
        self.actionInstaller = QAction(MainWindow)
        self.actionInstaller.setObjectName(u"actionInstaller")
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionshowColorDialog = QAction(MainWindow)
        self.actionshowColorDialog.setObjectName(u"actionshowColorDialog")
        self.actionshowSelectFont = QAction(MainWindow)
        self.actionshowSelectFont.setObjectName(u"actionshowSelectFont")
        self.actionAbout_Cairo = QAction(MainWindow)
        self.actionAbout_Cairo.setObjectName(u"actionAbout_Cairo")
        self.actionThirdPartyNotice = QAction(MainWindow)
        self.actionThirdPartyNotice.setObjectName(u"actionThirdPartyNotice")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(200, 0))
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 4, 0, 0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1250, 22))
        self.menubar.setContextMenuPolicy(Qt.NoContextMenu)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuCompile = QMenu(self.menubar)
        self.menuCompile.setObjectName(u"menuCompile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuAbout = QMenu(self.menuHelp)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuTest = QMenu(self.menubar)
        self.menuTest.setObjectName(u"menuTest")
        self.menuDialog = QMenu(self.menuTest)
        self.menuDialog.setObjectName(u"menuDialog")
        self.menuRun = QMenu(self.menuTest)
        self.menuRun.setObjectName(u"menuRun")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuToolbars = QMenu(self.menuView)
        self.menuToolbars.setObjectName(u"menuToolbars")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.FileToolBar = QToolBar(MainWindow)
        self.FileToolBar.setObjectName(u"FileToolBar")
        self.FileToolBar.setMovable(False)
        self.FileToolBar.setIconSize(QSize(18, 18))
        self.FileToolBar.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.FileToolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuCompile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuCompile.addAction(self.actionCompile)
        self.menuHelp.addAction(self.menuAbout.menuAction())
        self.menuAbout.addAction(self.actionAbout_MiFaceStudio)
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menuAbout.addAction(self.actionAbout_Cairo)
        self.menuAbout.addAction(self.actionThirdPartyNotice)
        self.menuTest.addAction(self.menuDialog.menuAction())
        self.menuTest.addAction(self.menuRun.menuAction())
        self.menuDialog.addAction(self.actionshowAboutWindow)
        self.menuDialog.addAction(self.actionshowDefaultInfoDialog)
        self.menuDialog.addAction(self.actionshowToast)
        self.menuDialog.addAction(self.actionshowColorDialog)
        self.menuDialog.addAction(self.actionshowSelectFont)
        self.menuRun.addAction(self.actionInstaller)
        self.menuView.addAction(self.actionExplorer)
        self.menuView.addAction(self.actionAttributes)
        self.menuView.addAction(self.actionToolbox)
        self.menuView.addAction(self.actionResources)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuToolbars.addAction(self.actionEdit)
        self.menuToolbars.addAction(self.actionFile)
        self.menuToolbars.addAction(self.actionLayout)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.FileToolBar.addAction(self.actionNewFile)
        self.FileToolBar.addAction(self.actionOpenFile)
        self.FileToolBar.addAction(self.actionUndo)
        self.FileToolBar.addAction(self.actionRedo)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Mi Face Studio", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save...", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as...", None))
#if QT_CONFIG(shortcut)
        self.actionSave_as.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout_MiFaceStudio.setText(QCoreApplication.translate("MainWindow", u"About Mi Face Studio", None))
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(shortcut)
        self.actionPreferences.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionCompile.setText(QCoreApplication.translate("MainWindow", u"Compile...", None))
#if QT_CONFIG(shortcut)
        self.actionCompile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+K", None))
#endif // QT_CONFIG(shortcut)
        self.actionshowAboutWindow.setText(QCoreApplication.translate("MainWindow", u"showAboutWindow", None))
        self.actionshowDefaultInfoDialog.setText(QCoreApplication.translate("MainWindow", u"showDefaultCriticalDialog", None))
        self.actionExplorer.setText(QCoreApplication.translate("MainWindow", u"Explorer", None))
        self.actionAttributes.setText(QCoreApplication.translate("MainWindow", u"Attributes", None))
        self.actionResources.setText(QCoreApplication.translate("MainWindow", u"Resources", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionshowToast.setText(QCoreApplication.translate("MainWindow", u"showToast", None))
        self.actionToolbox.setText(QCoreApplication.translate("MainWindow", u"Toolbox", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.actionFile.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.actionLayout.setText(QCoreApplication.translate("MainWindow", u"Layout", None))
        self.actionNewFile.setText(QCoreApplication.translate("MainWindow", u"New...", None))
#if QT_CONFIG(tooltip)
        self.actionNewFile.setToolTip(QCoreApplication.translate("MainWindow", u"New File", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNewFile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenFile.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
#if QT_CONFIG(tooltip)
        self.actionOpenFile.setToolTip(QCoreApplication.translate("MainWindow", u"Open File", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenFile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y, Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionInstaller.setText(QCoreApplication.translate("MainWindow", u"Installer", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionshowColorDialog.setText(QCoreApplication.translate("MainWindow", u"showColorDialog", None))
        self.actionshowSelectFont.setText(QCoreApplication.translate("MainWindow", u"showSelectFont", None))
        self.actionAbout_Cairo.setText(QCoreApplication.translate("MainWindow", u"About Cairo", None))
        self.actionThirdPartyNotice.setText(QCoreApplication.translate("MainWindow", u"Third Party Notices", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuCompile.setTitle(QCoreApplication.translate("MainWindow", u"Compile", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"About", None))
        self.menuTest.setTitle(QCoreApplication.translate("MainWindow", u"Test", None))
        self.menuDialog.setTitle(QCoreApplication.translate("MainWindow", u"Dialog...", None))
        self.menuRun.setTitle(QCoreApplication.translate("MainWindow", u"Run...", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuToolbars.setTitle(QCoreApplication.translate("MainWindow", u"Toolbars", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.FileToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"File Toolbar", None))
    # retranslateUi

